In [101]:
import numpy as np
from sympy import init_session
init_session(use_latex=True)

IPython console for SymPy 1.9 (Python 3.9.7-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at https://docs.sympy.org/1.9/



## Repaso Matrices - Taller 3

Este taller debe ser entregado a más tardar el viernes 3 de noviembre a medianoche (11:59pm).

### 1. Multiplicación de matrices

**[20 pts]** Construya el algoritmo de multiplicación de matrices y encuentre el resultado de las siguientes operaciones.

a.

 <img src ='./img/matrix1.png' width=200px>

 b.
 
  <img src ='./img/matrix2.png' width=200px>

  c. 

  <img src ='./img/matrix3.png' width=200px>

  **[10 pts]** Utilizando dos matrices cuadradas, demuestre que la multiplicación no es conmutativa.

In [102]:
def mulM(A,B):

    if len(np.shape(A)) == 1:
        A = np.reshape(A,(1,len(A)))

    if len(np.shape(B)) == 1:
        B = np.reshape(B,(len(B),1))

    AB = np.zeros(shape=(np.shape(A)[0],np.shape(B)[1]))

    if np.shape(A)[1] == np.shape(B)[0]:
        for i in range(np.shape(B)[1]):
            for j in range(np.shape(A)[0]):
                sum = 0
                for k in range(np.shape(A)[1]):
                    sum += A[j][k]*B[k][i]
                    
                AB[j][i] = sum
    else:
        AB = None
        print('Multiplicación no está definida')
    
    return AB

a)

In [103]:
A = np.array([[5.,-4.,-2.],
              [5.,-5.,4.],
              [2.,5.,-4.],
              [-5.,4.,3.],
              [3.,-4.,-3.]])

B = np.array([5.,-2.,-3.])

mulM(A,B)
#np.matmul(A,B)

array([[ 39.],
       [ 23.],
       [ 12.],
       [-42.],
       [ 32.]])

b)

In [104]:
A = np.array([[0.,-1.,-1.,3.],
              [5.,-5.,-2.,2.],
              [1.,0.,4.,5.]])

B = np.array([[0.,-3.],
              [-2.,-1.],
              [3.,-3.]])

mulM(A,B)
#np.matmul(A,B)

Multiplicación no está definida


c)

In [105]:
A = np.array([[2.,-5.,5.,1.],
              [5.,2.,-7.,-6.],
              [-6.,-1.,7.,-4.],
              [5.,4.,1.,-5.]])

B = np.array([[0.,4.,-7.,1.,-6.],
              [-1.,-6.,-5.,1.,1.],
              [2.,-1.,-6.,5.,-5.],
              [-3.,-6.,6.,3.,5.]])

mulM(A,B)
#np.matmul(A,B)

array([[ 12.,  27., -13.,  25., -37.],
       [  2.,  51., -39., -46., -23.],
       [ 27.,  -1., -19.,  16., -20.],
       [ 13.,  25., -91.,  -1., -56.]])

No conmutividad.

A*B =! B*A

In [106]:
A = np.array([[1.,2.],
              [3.,4.]])

B = np.array([[5.,6.],
              [7.,8.]])

mulM(A,B) == mulM(B,A)

array([[False, False],
       [False, False]])

### 2. Reducción gaussiana
**[40 pts]** Utilizando el algoritmo de reducción Gaussiana, resuelva los siguientes sistemas de ecuaciones:

a.

 <img src ='./img/gaussian1.png' width=300px align=center>

 b.

 <img src ='./img/gaussian2.png' width=300px>

In [107]:
def gaussian_elimination(A: np.array,b: np.array):
    '''
    Args:
        A (np.array): Matriz de coeficientes cuadrada (n x n).
        b (np.array): Vector de constantes de longitud n

    Returns:
        M (np.array): Matriz aumentada [A|b] reducida utilizando el algoritmo de eliminación Gaussiana
    '''
    n = np.shape(A)[0]
    M = np.zeros(shape=(n,n+1))
    M[:,0:n] = A
    M[:,n] = b
    
    i_ = 1
    for j in range(0,n-1):
        
        for i in range(i_,n):
            #print(i,j)
            M[i,:] -= (M[i,j]/M[j,j])*M[j,:]
        i_ +=1

    return M

def back_substitution(A, b):
    '''
    Args:
        A (np.array): Matriz de coeficientes triangular superior
        b (np.arra): vector de constantes
        
    '''

    n = np.shape(A)[0]

    x = np.zeros(n)

    for i in range(n-1,-1,-1):
        sum = b[i]
        for j in range(n-1,i,-1):
            sum -= A[i,j]*x[j]
        x[i] = sum/A[i,i]

    return x

a)

In [108]:
A = np.array([[3.,1.,-1.],
              [1.,-2.,1.],
              [4.,-1.,1.]])
n = np.shape(A)[0]
b = np.array([2.,0.,3.])

A_ = gaussian_elimination(A,b)
Ar = A_[:,:n]
br = A_[:,n]

x = back_substitution(Ar,br)
print(x)
#print(np.linalg.solve(A,b))

[0.71428571 0.85714286 1.        ]


b)

In [109]:
A = np.array([[1.,1.,1.],
              [0.,-8.,10.],
              [4.,-8.,0.]])
n = np.shape(A)[0]
b = np.array([0.,0.,6.])

A_ = gaussian_elimination(A,b)

A_ = gaussian_elimination(A,b)
Ar = A_[:,:n]
br = A_[:,n]

x = back_substitution(Ar,br)
print(x)
#print(np.linalg.solve(A,b))

[ 0.71052632 -0.39473684 -0.31578947]


### 3. Valores y vectores propios

**[30 pts]** Un sistema de tres osciladores acoplados, tiene las siguientes ecuaciones de movimiento:

<img src='./img/eqmotion.png' width=200>

Al reemplazar $x_1=c_1e^{i\omega t},x_2=c_2e^{i\omega t},x_3=c_3e^{i\omega t}$ se obtienen las siguientes ecuaciones algebraicas

<img src='./img/algeq.png'  width=200>

Para encontrar las frecuencias, se puede pensar lo anterior como un problema de valor propio regido por la ecuación

$M\vec{v} = -\omega^2 \vec{v}$

donde $\vec{v}$ es el vector de amplitudes $c_1,c_2,c_3$ y $-\omega^2$ los valores propios. Utilizando el método de la potencia, encuentre la frecuencia máxima y mínima de oscilación del sistema y sus amplitudes asociadas para cada caso (modo normal). En su solución pruebe $k_{11}=k_{22}=k_{33}=-2\kappa, k_{12}=k_{21}=k_{23}=k_{32}=\kappa, k_{13}=k_{31}=0$.




In [ ]:
"""def GetValorAndVectorMax(A,v,its=11):
    v = Matrix(v)
    for i in range(its):
        vn = v.normalized()
        v = A*vn
        lam = vn.T*v
    
    v = v.normalized()

    return lam,v

def GetValorAndVectorMinor(A,v,its=11):
    A = A.inv()
    v = Matrix(v)
    for i in range(its):
        vn = v.normalized()
        v = A*vn
        lam = vn.T*v

    v = v.normalized()

    return 1/lam, v"""

In [110]:
def GetValorAndVectorMax(A,v,its=11):
    
    for i in range(its):
        vn = v/(np.linalg.norm(v))
        v = mulM(A,vn)
        lam = mulM(vn.T,v)

    return lam,v/(np.linalg.norm(v))

def GetValorAndVectorMinor(A,v,its=11):
    A = np.linalg.inv(A)
    for i in range(its):
        vn = v/(np.linalg.norm(v))
        v = mulM(A,vn)
        lam = mulM(vn.T,v)

    return 1/lam,v/(np.linalg.norm(v))

In [111]:
k , m1 , m2 , m3 = symbols('k m1 m2 m3', real=True)

A = Matrix([[-2.*k/m1,k/m1,0.],
            [k/m2,-2.*k/m2,k/m2],
            [0.,k/m3,-2.*k/m3]])

A_np = (lambdify((k,m1,m2,m3),A,'numpy'))
A_numerica = (A_np(1,1,1,1))
v = np.array([1,1,1])

In [112]:
GetValorAndVectorMax(A_numerica,v)

(array([[-3.41421356]]),
 array([[-0.50000001],
        [ 0.70710677],
        [-0.50000001]]))

In [113]:
GetValorAndVectorMinor(A_numerica,v)

(array([[-0.58578644]]),
 array([[-0.5       ],
        [-0.70710678],
        [-0.5       ]]))